### ISSUE TITLE
Upgrade to irods-docker v4.3.3-1

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-docker-compose#34]
This depends on bihealth/irods-docker#16.

## Tasks

- [x] Update env examples to release version once tagged and pushed
- [x] Add `IRODS_PASSWORD_MIN_TIME` env var
- [x] Ensure iRODS works in staging
- [x] Update davrods, ensure both normal and ticket URLs work
- [x] Fix iRODS syslog access problem (see comments)

**Comment by mikkonie** [comment]
When restarting the environment, I suddenly started getting iRODS syslog access errors despite not changing anything in my config:

```
irods-1       | rsyslogd: file '/var/log/irods/irods.log': open error: Permission denied [v8.2001.0 try https://www.rsyslog.com/e/2433 ]
```

I'll have to see why this is.

**Comment by mikkonie** [comment]
Done.
