### ISSUE TITLE
Upgrade to davrods-docker v4.3.3_1.5.1-1

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-docker-compose#63]
Once I'm able to tag a release for this image, we should update. See bihealth/davrods-docker#3.

## Tasks

- [x] Make sure image works in dev
- [x] Make sure image vorks in staging
- [x] Update docs and env examples as needed
- [x] Update env examples to release version once tagged and pushed

**Comment by mikkonie** [comment]
Env updated, still need to make sure all works as expected before closing the issue.

**Comment by mikkonie** [comment]
Everything appears to work in staging, this can be closed.
